/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as TournamentsRouteImport } from './pages/tournaments'
import { Route as TeamsRouteImport } from './pages/teams'
import { Route as ProfileRouteImport } from './pages/profile'
import { Route as OnboardingRouteImport } from './pages/onboarding'
import { Route as MatchesRouteImport } from './pages/matches'
import { Route as HomeRouteImport } from './pages/home'
import { Route as CertificatesRouteImport } from './pages/certificates'
import { Route as IndexRouteImport } from './pages/index'
import { Route as TournamentsTournamentIdRouteImport } from './pages/tournaments.$tournamentId'
import { Route as TeamsTeamIdRouteImport } from './pages/teams.$teamId'
import { Route as PlayersPlayerIdRouteImport } from './pages/players.$playerId'
import { Route as MatchesMatchIdRouteImport } from './pages/matches.$matchId'
import { Route as AuthCallbackRouteImport } from './pages/auth.callback'
import { Route as MatchesMatchIdScoreRouteImport } from './pages/matches.$matchId.score'

const TournamentsRoute = TournamentsRouteImport.update({
  id: '/tournaments',
  path: '/tournaments',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsRoute = TeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesRoute = MatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificatesRoute = CertificatesRouteImport.update({
  id: '/certificates',
  path: '/certificates',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentsTournamentIdRoute = TournamentsTournamentIdRouteImport.update({
  id: '/$tournamentId',
  path: '/$tournamentId',
  getParentRoute: () => TournamentsRoute,
} as any)
const TeamsTeamIdRoute = TeamsTeamIdRouteImport.update({
  id: '/$teamId',
  path: '/$teamId',
  getParentRoute: () => TeamsRoute,
} as any)
const PlayersPlayerIdRoute = PlayersPlayerIdRouteImport.update({
  id: '/players/$playerId',
  path: '/players/$playerId',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesMatchIdRoute = MatchesMatchIdRouteImport.update({
  id: '/$matchId',
  path: '/$matchId',
  getParentRoute: () => MatchesRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesMatchIdScoreRoute = MatchesMatchIdScoreRouteImport.update({
  id: '/score',
  path: '/score',
  getParentRoute: () => MatchesMatchIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/certificates': typeof CertificatesRoute
  '/home': typeof HomeRoute
  '/matches': typeof MatchesRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/teams': typeof TeamsRouteWithChildren
  '/tournaments': typeof TournamentsRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/matches/$matchId': typeof MatchesMatchIdRouteWithChildren
  '/players/$playerId': typeof PlayersPlayerIdRoute
  '/teams/$teamId': typeof TeamsTeamIdRoute
  '/tournaments/$tournamentId': typeof TournamentsTournamentIdRoute
  '/matches/$matchId/score': typeof MatchesMatchIdScoreRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/certificates': typeof CertificatesRoute
  '/home': typeof HomeRoute
  '/matches': typeof MatchesRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/teams': typeof TeamsRouteWithChildren
  '/tournaments': typeof TournamentsRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/matches/$matchId': typeof MatchesMatchIdRouteWithChildren
  '/players/$playerId': typeof PlayersPlayerIdRoute
  '/teams/$teamId': typeof TeamsTeamIdRoute
  '/tournaments/$tournamentId': typeof TournamentsTournamentIdRoute
  '/matches/$matchId/score': typeof MatchesMatchIdScoreRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/certificates': typeof CertificatesRoute
  '/home': typeof HomeRoute
  '/matches': typeof MatchesRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/teams': typeof TeamsRouteWithChildren
  '/tournaments': typeof TournamentsRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/matches/$matchId': typeof MatchesMatchIdRouteWithChildren
  '/players/$playerId': typeof PlayersPlayerIdRoute
  '/teams/$teamId': typeof TeamsTeamIdRoute
  '/tournaments/$tournamentId': typeof TournamentsTournamentIdRoute
  '/matches/$matchId/score': typeof MatchesMatchIdScoreRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/certificates'
    | '/home'
    | '/matches'
    | '/onboarding'
    | '/profile'
    | '/teams'
    | '/tournaments'
    | '/auth/callback'
    | '/matches/$matchId'
    | '/players/$playerId'
    | '/teams/$teamId'
    | '/tournaments/$tournamentId'
    | '/matches/$matchId/score'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/certificates'
    | '/home'
    | '/matches'
    | '/onboarding'
    | '/profile'
    | '/teams'
    | '/tournaments'
    | '/auth/callback'
    | '/matches/$matchId'
    | '/players/$playerId'
    | '/teams/$teamId'
    | '/tournaments/$tournamentId'
    | '/matches/$matchId/score'
  id:
    | '__root__'
    | '/'
    | '/certificates'
    | '/home'
    | '/matches'
    | '/onboarding'
    | '/profile'
    | '/teams'
    | '/tournaments'
    | '/auth/callback'
    | '/matches/$matchId'
    | '/players/$playerId'
    | '/teams/$teamId'
    | '/tournaments/$tournamentId'
    | '/matches/$matchId/score'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CertificatesRoute: typeof CertificatesRoute
  HomeRoute: typeof HomeRoute
  MatchesRoute: typeof MatchesRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
  ProfileRoute: typeof ProfileRoute
  TeamsRoute: typeof TeamsRouteWithChildren
  TournamentsRoute: typeof TournamentsRouteWithChildren
  AuthCallbackRoute: typeof AuthCallbackRoute
  PlayersPlayerIdRoute: typeof PlayersPlayerIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tournaments': {
      id: '/tournaments'
      path: '/tournaments'
      fullPath: '/tournaments'
      preLoaderRoute: typeof TournamentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams': {
      id: '/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof TeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches': {
      id: '/matches'
      path: '/matches'
      fullPath: '/matches'
      preLoaderRoute: typeof MatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificates': {
      id: '/certificates'
      path: '/certificates'
      fullPath: '/certificates'
      preLoaderRoute: typeof CertificatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournaments/$tournamentId': {
      id: '/tournaments/$tournamentId'
      path: '/$tournamentId'
      fullPath: '/tournaments/$tournamentId'
      preLoaderRoute: typeof TournamentsTournamentIdRouteImport
      parentRoute: typeof TournamentsRoute
    }
    '/teams/$teamId': {
      id: '/teams/$teamId'
      path: '/$teamId'
      fullPath: '/teams/$teamId'
      preLoaderRoute: typeof TeamsTeamIdRouteImport
      parentRoute: typeof TeamsRoute
    }
    '/players/$playerId': {
      id: '/players/$playerId'
      path: '/players/$playerId'
      fullPath: '/players/$playerId'
      preLoaderRoute: typeof PlayersPlayerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches/$matchId': {
      id: '/matches/$matchId'
      path: '/$matchId'
      fullPath: '/matches/$matchId'
      preLoaderRoute: typeof MatchesMatchIdRouteImport
      parentRoute: typeof MatchesRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches/$matchId/score': {
      id: '/matches/$matchId/score'
      path: '/score'
      fullPath: '/matches/$matchId/score'
      preLoaderRoute: typeof MatchesMatchIdScoreRouteImport
      parentRoute: typeof MatchesMatchIdRoute
    }
  }
}

interface MatchesMatchIdRouteChildren {
  MatchesMatchIdScoreRoute: typeof MatchesMatchIdScoreRoute
}

const MatchesMatchIdRouteChildren: MatchesMatchIdRouteChildren = {
  MatchesMatchIdScoreRoute: MatchesMatchIdScoreRoute,
}

const MatchesMatchIdRouteWithChildren = MatchesMatchIdRoute._addFileChildren(
  MatchesMatchIdRouteChildren,
)

interface MatchesRouteChildren {
  MatchesMatchIdRoute: typeof MatchesMatchIdRouteWithChildren
}

const MatchesRouteChildren: MatchesRouteChildren = {
  MatchesMatchIdRoute: MatchesMatchIdRouteWithChildren,
}

const MatchesRouteWithChildren =
  MatchesRoute._addFileChildren(MatchesRouteChildren)

interface TeamsRouteChildren {
  TeamsTeamIdRoute: typeof TeamsTeamIdRoute
}

const TeamsRouteChildren: TeamsRouteChildren = {
  TeamsTeamIdRoute: TeamsTeamIdRoute,
}

const TeamsRouteWithChildren = TeamsRoute._addFileChildren(TeamsRouteChildren)

interface TournamentsRouteChildren {
  TournamentsTournamentIdRoute: typeof TournamentsTournamentIdRoute
}

const TournamentsRouteChildren: TournamentsRouteChildren = {
  TournamentsTournamentIdRoute: TournamentsTournamentIdRoute,
}

const TournamentsRouteWithChildren = TournamentsRoute._addFileChildren(
  TournamentsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CertificatesRoute: CertificatesRoute,
  HomeRoute: HomeRoute,
  MatchesRoute: MatchesRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
  ProfileRoute: ProfileRoute,
  TeamsRoute: TeamsRouteWithChildren,
  TournamentsRoute: TournamentsRouteWithChildren,
  AuthCallbackRoute: AuthCallbackRoute,
  PlayersPlayerIdRoute: PlayersPlayerIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
